spring:
  application:
    name: app

  datasource:
    url: jdbc:h2:file:C:/data/appdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: PUBLIC
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: PUBLIC
    baseline-on-migrate: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

springdoc:
  swagger-ui:
    enabled: true
    path: /api/swagger-ui-custom.html
    operationsSorter: method