CREATE TABLE IF NOT EXISTS role (
  role VARCHAR(10) NOT NULL,
  PRIMARY KEY (role)
);

CREATE TABLE IF NOT EXISTS football_position (
  position_name VARCHAR(50) NOT NULL,
  PRIMARY KEY (position_name)
);

CREATE TABLE IF NOT EXISTS app_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(40) NOT NULL,
  password VARCHAR(250) NOT NULL,
  name VARCHAR(250) NOT NULL,
  nickname VARCHAR(50),
  birthdate TIMESTAMP,
  is_regular_member BOOLEAN NOT NULL DEFAULT FALSE,
  user_role VARCHAR(10) NOT NULL,
  grade_average DECIMAL(4,2),
  last_grade DECIMAL(4,2),
  CONSTRAINT uk_user_username UNIQUE (username),
  FOREIGN KEY (user_role) REFERENCES role(role)
);

CREATE INDEX IF NOT EXISTS idx_user_role ON app_user (user_role);

CREATE TABLE IF NOT EXISTS football_match (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_date TIMESTAMP NOT NULL,
  max_players INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS match_player (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_user BIGINT NOT NULL,
  id_match BIGINT NOT NULL,
  team INTEGER,
  subscription_date TIMESTAMP NOT NULL,
  was_present BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT uk_match_player_user_match UNIQUE (id_user, id_match),
  FOREIGN KEY (id_user) REFERENCES app_user(id),
  FOREIGN KEY (id_match) REFERENCES football_match(id)
);

CREATE INDEX IF NOT EXISTS idx_match_player_user ON match_player (id_user);
CREATE INDEX IF NOT EXISTS idx_match_player_match ON match_player (id_match);

CREATE TABLE IF NOT EXISTS evaluation (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_match BIGINT NOT NULL,
  id_user_evaluator BIGINT NOT NULL,
  id_user_evaluatee BIGINT NOT NULL,
  grade DECIMAL(4,2) NOT NULL,
  FOREIGN KEY (id_match) REFERENCES football_match(id),
  FOREIGN KEY (id_user_evaluator) REFERENCES app_user(id),
  FOREIGN KEY (id_user_evaluatee) REFERENCES app_user(id)
);

CREATE INDEX IF NOT EXISTS idx_evaluation_match ON evaluation (id_match);
CREATE INDEX IF NOT EXISTS idx_evaluation_evaluator ON evaluation (id_user_evaluator);
CREATE INDEX IF NOT EXISTS idx_evaluation_evaluatee ON evaluation (id_user_evaluatee);

CREATE TABLE IF NOT EXISTS player_position (
  id_user BIGINT NOT NULL,
  position_name VARCHAR(50) NOT NULL,
  PRIMARY KEY (id_user, position_name),
  FOREIGN KEY (id_user) REFERENCES app_user(id)
);

CREATE INDEX IF NOT EXISTS idx_player_position_position ON player_position (position_name);

INSERT INTO role (role) VALUES ('ADMIN'), ('PLAYER');

INSERT INTO football_position (position_name) VALUES
  ('GOALKEEPER'),
  ('DEFENDER'),
  ('WINGBACK'),
  ('MIDFIELDER'),
  ('STRIKER');